import bcrypt from 'bcryptjs';
const data = {
  users:[
    {
        name:'John',
        email:'admin@example.com',
        password:bcrypt.hashSync('123456'),
        isAdmin:true,
    },
    {
        name:'Manju',
        email:'user@example.com',
        password:bcrypt.hashSync('123456'),
        isAdmin:false,
    }
  ],
    products: [
        {
            // _id: '1',
            name: 'nike-slim-shirt',
            slug: 'nike-slim-shirt',
            category: "Shirts",
            image: '/images/pic1.jpg',
            price: 600,
            countInStock: 8,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'Good Quality',
        },
        {
            // _id: '2',
            name: 'panther-slim-shirt',
            slug: 'adidas-shoes',
            category: "Shirts",
            image: '/images/pic2.jpg',
            price: 600,
            countInStock: 100,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'Good Quality',
        },
        {
            // _id: '3',
            name: 'iron slim shirt',
            slug: 'puma-shoes',
            category: "Shirts",
            image: '/images/pic3.jpg',
            price: 600,
            countInStock: 100,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            description: 'Good Quality',
        },
        {
            // _id: '4',
            name: 'magic slim shirt 1',
            slug: 'magic slim shirt 1',
            category: "Shirts",
            image: '/images/pic4.jpg',
            price: 600,
            countInStock: 0,
            brand: 'Nike',
            rating: 3,
            numReviews: 8,
            description: 'Good Quality',
        },
        {
            // _id: '4',
            name: 'magic slim shirt 2',
            slug: 'magic slim shirt 2',
            category: "Shirts",
            image: '/images/pic5.jpg',
            price: 600,
            countInStock: 0,
            brand: 'Nike',
            rating: 3,
            numReviews: 8,
            description: 'Good Quality',
        },
        {
            // _id: '4',
            name: 'magic slim shirt 3',
            slug: 'Bata-power',
            category: "Shirts",
            image: '/images/pic6.jpg',
            price: 600,
            countInStock: 0,
            brand: 'Nike',
            rating: 3,
            numReviews: 8,
            description: 'Good Quality',
        },

    ],
};


export default data;